<a href="https://colab.research.google.com/github/HfzhImn/2025_Artificial-Intelligence_TI-1B/blob/main/JOBSHEET%2002%20OPERASI%20MATEMATIKA%2C%20VEKTOR%2C%20MATRIKS%20DAN%20TIPE%20DATA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Jobsheet 2: Operasi Matematika, Vektor,Matriks, dan Tipe Data

##Praktikum 02

In [ ]:
x = min(5, 10, 25)
y = max(6, 12, 18)
print(x)
print(y)

5
18


In [ ]:
x = abs(-7.25)
print(x)

7.25


In [ ]:
import math
x = math.pow(4, 3)
print(x)

64.0


In [ ]:
import math
x = math.sqrt(64)
print(x)

8.0


In [ ]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print(x)
print(y)

2
1


In [ ]:
import math
x = math.pi
print(x)

3.141592653589793


##Praktikum 03

In [ ]:
import math
# 1. Trigonometri (Sinus, Kosinus, Tangen)
x = math.sin(math.pi / 2)
y = math.cos(0)
z = math.tan(math.pi / 4)
print("Trigonometri:")
print("sin(90°) =", x)
print("cos(0°) =", y)
print("tan(45°) =", z)
print()

# 2. Logaritma (Natural & Basis 10)
a = math.log(2.71828)
b = math.log10(100)
print("Logaritma:")
print("log(e) =", a)
print("log10(100) =", b)
print()

# 3. Konversi Derajat & Jarak
c = math.degrees(math.pi)
d = math.dist([0, 0], [3, 4])
print("Konversi Derajat & Jarak:")
print("math.degrees(π) =", c)
print("Jarak antara (0,0) dan (3,4) =", d)
print()

# 4. Faktorial
e = math.factorial(5)
print("Faktorial:")
print("5! =", e)
print()

# 5. Operasi Matematika Lainnya (fmod & isnan)
f = math.fmod(20, 3)
g = math.isnan(float('nan'))
print("Operasi Lainnya:")
print("math.fmod(20, 3) =", f)
print("Apakah 'nan' adalah NaN? =", g)
print()

# 6. Fungsi Gamma
h = math.gamma(5)
print("Fungsi Gamma:")
print("Gamma(5) =", h)
print()

# 7. Permutasi
i = math.perm(5, 3)
print("Permutasi:")
print("Permutasi 5P3 =", i)


Trigonometri:
sin(90°) = 1.0
cos(0°) = 1.0
tan(45°) = 0.9999999999999999

Logaritma:
log(e) = 0.999999327347282
log10(100) = 2.0

Konversi Derajat & Jarak:
math.degrees(π) = 180.0
Jarak antara (0,0) dan (3,4) = 5.0

Faktorial:
5! = 120

Operasi Lainnya:
math.fmod(20, 3) = 2.0
Apakah 'nan' adalah NaN? = True

Fungsi Gamma:
Gamma(5) = 24.0

Permutasi:
Permutasi 5P3 = 60


##Praktikum 04

In [ ]:

import numpy as np
# -------------------------------------------------
# Bagian A: Operasi Matriks (Penjumlahan Matriks)
# -------------------------------------------------

# Membuat Matriks A dan B menggunakan np.array()
A = np.array([[80, 30, 25],
              [50, 20, 10]])

B = np.array([[30, 60, 15],
              [10, 30, 30]])

# Melakukan operasi penjumlahan matriks A + B
hasil_matriks = A + B

# Menampilkan hasil penjumlahan matriks
print("Hasil Penjumlahan Matriks A + B:")
print(hasil_matriks)
print()


# -------------------------------------------------
# Bagian B: Operasi Dot Product (Perkalian Vektor)
# -------------------------------------------------

# Membuat Vektor A dan B menggunakan np.array()
Vektor_A = np.array([10, 20, 15])
Vektor_B = np.array([16, 67, 35])

# Melakukan operasi dot product menggunakan np.dot()
hasil_dot_product = np.dot(Vektor_A, Vektor_B)

# Menampilkan hasil dari operasi dot product
print("Hasil Dot Product dari Vektor A dan B:")
print(hasil_dot_product)
print()


# -------------------------------------------------
# Bagian C: Operasi Cross Product (Perkalian Silang Vektor)
# -------------------------------------------------

# Menghitung cross product dari Vektor_A dan Vektor_B menggunakan np.cross()
hasil_cross_product = np.cross(Vektor_A, Vektor_B)

# Menampilkan hasil dari operasi cross product
print("Hasil Cross Product dari Vektor A dan B:")
print(hasil_cross_product)


Hasil Penjumlahan Matriks A + B:
[[110  90  40]
 [ 60  50  40]]

Hasil Dot Product dari Vektor A dan B:
2025

Hasil Cross Product dari Vektor A dan B:
[-305 -110  350]


##Tugas Praktikum